import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:share_plus/share_plus.dart';
import '../models/models.dart';
import '../theme/app_theme.dart';
import '../widgets/tm_widgets.dart';
import 'results_screen.dart';

// ════════════════════════════════════════════════════════
// PROJECT DETAIL SCREEN
// ════════════════════════════════════════════════════════

class ProjectDetailScreen extends StatefulWidget {
  final TileProject project;

  const ProjectDetailScreen({super.key, required this.project});

  @override
  State<ProjectDetailScreen> createState() => _ProjectDetailScreenState();
}

class _ProjectDetailScreenState extends State<ProjectDetailScreen> {
  late TileProject _project;

  @override
  void initState() {
    super.initState();
    _project = widget.project;
  }

  void _removeRoom(String roomId) {
    setState(() => _project = _project.removeRoom(roomId));
  }

  void _changeStatus(ProjectStatus status) {
    setState(() => _project = _project.copyWith(status: status));
  }

  void _shareQuote() {
    final buf = StringBuffer()
      ..writeln('QUOTE — ${_project.name}')
      ..writeln('─' * 36);
    if (_project.clientName != null) {
      buf.writeln('Client:   ${_project.clientName}');
    }
    if (_project.siteAddress != null) {
      buf.writeln('Site:     ${_project.siteAddress}');
    }
    buf.writeln('Date:     ${DateFormat('d MMM yyyy').format(_project.createdAt)}');
    buf.writeln();

    for (final room in _project.rooms) {
      final roomTotal = NumberFormat.currency(
        symbol: _project.currencySymbol,
        decimalDigits: 2,
      ).format(room.totalCost);

      buf.writeln('• ${room.roomName}');
      buf.writeln(
          '  ${room.floorArea.toStringAsFixed(2)} m²  ·  ${room.boxesRequired} boxes  ·  $roomTotal');
    }

    buf.writeln();
    buf.writeln('─' * 36);
    buf.writeln('TOTAL: ${NumberFormat.currency(symbol: _project.currencySymbol, decimalDigits: 2).format(_project.grandTotal)}');
    buf.writeln('─' * 36);
    buf.writeln('Generated by Tilemate');

    Share.share(buf.toString(), subject: 'Quote: ${_project.name}');
  }

  @override
  Widget build(BuildContext context) {
    return PopScope(
      canPop: false,
      onPopInvokedWithResult: (didPop, result) {
        if (!didPop) {
          Navigator.of(context).pop(_project);
        }
      },
      child: Scaffold(
        backgroundColor: AppTheme.bg,
        body: CustomScrollView(
          slivers: [
            SliverAppBar(
              pinned: true,
              backgroundColor: AppTheme.bg,
              expandedHeight: 160,
              leading: IconButton(
                icon: const Icon(Icons.arrow_back),
                onPressed: () => Navigator.of(context).pop(_project),
              ),
              actions: [
                IconButton(
                  icon: const Icon(Icons.share_outlined),
                  onPressed: _shareQuote,
                ),
                PopupMenuButton<ProjectStatus>(
                  icon: const Icon(Icons.more_vert),
                  color: AppTheme.surface,
                  onSelected: _changeStatus,
                  itemBuilder: (_) => ProjectStatus.values.map((s) {
                    return PopupMenuItem(
                      value: s,
                      child: Text(s.displayName,
                          style: const TextStyle(
                              color: AppTheme.textHigh, fontSize: 14)),
                    );
                  }).toList(),
                ),
              ],
              flexibleSpace: FlexibleSpaceBar(
                background: _ProjectHero(project: _project),
              ),
            ),

            SliverPadding(
              padding: const EdgeInsets.fromLTRB(16, 12, 16, 40),
              sliver: SliverList(
                delegate: SliverChildListDelegate([
                  // Client info
                  if (_project.clientName != null ||
                      _project.siteAddress != null) ...[
                    TmCard(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const TmSectionLabel('Client'),
                          if (_project.clientName != null)
                            _InfoRow(Icons.person_outline, _project.clientName!),
                          if (_project.clientPhone != null)
                            _InfoRow(Icons.phone_outlined, _project.clientPhone!),
                          if (_project.clientEmail != null)
                            _InfoRow(Icons.email_outlined, _project.clientEmail!),
                          if (_project.siteAddress != null)
                            _InfoRow(Icons.location_on_outlined, _project.siteAddress!),
                        ],
                      ),
                    ),
                    const SizedBox(height: 12),
                  ],

                  // Summary stats
                  TmCard(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const TmSectionLabel('Project Summary'),
                        const SizedBox(height: 8),
                        GridView.count(
                          crossAxisCount: 2,
                          shrinkWrap: true,
                          physics: const NeverScrollableScrollPhysics(),
                          crossAxisSpacing: 8,
                          mainAxisSpacing: 8,
                          childAspectRatio: 2.0,
                          children: [
                            TmStatChip(
                              label: 'Total Area',
                              value: '${_project.totalFloorArea.toStringAsFixed(1)} m²',
                            ),
                            TmStatChip(
                              label: 'Total Boxes',
                              value: '${_project.totalBoxesRequired}',
                              icon: Icons.inventory_2_outlined,
                            ),
                            TmStatChip(
                              label: 'Tile Cost',
                              value: NumberFormat.compactCurrency(
                                      symbol: _project.currencySymbol)
                                  .format(_project.totalTileCost),
                            ),
                            TmStatChip(
                              label: 'Labour',
                              value: NumberFormat.compactCurrency(
                                      symbol: _project.currencySymbol)
                                  .format(_project.totalLaborCost),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(height: 12),

                  // Room list
                  TmSectionLabel(
                    '${_project.roomCount} Room${_project.roomCount != 1 ? 's' : ''}',
                  ),

                  if (_project.isEmpty)
                    Padding(
                      padding: const EdgeInsets.symmetric(vertical: 16),
                      child: Center(
                        child: Text(
                          'No rooms yet. Use the calculator and save to this project.',
                          style: const TextStyle(
                              fontSize: 12, color: AppTheme.textLow),
                          textAlign: TextAlign.center,
                        ),
                      ),
                    )
                  else
                    ..._project.rooms.map((room) => Padding(
                          padding: const EdgeInsets.only(bottom: 8),
                          child: _RoomCard(
                            room: room,
                            currencySymbol: _project.currencySymbol,
                            onViewResult: () => Navigator.of(context).push(
                              MaterialPageRoute(
                                builder: (_) =>
                                    ResultsScreen(calculation: room),
                              ),
                            ),
                            onDelete: () => _removeRoom(room.id),
                          ),
                        )),

                  const SizedBox(height: 20),

                  // Grand total
                  TmCard(
                    highlight: true,
                    child: Row(
                      children: [
                        const Expanded(
                          child: Text(
                            'GRAND TOTAL',
                            style: TextStyle(
                              fontSize: 13,
                              fontWeight: FontWeight.w900,
                              letterSpacing: 0.8,
                              color: AppTheme.textHigh,
                            ),
                          ),
                        ),
                        Text(
                          NumberFormat.currency(
                            symbol: _project.currencySymbol,
                            decimalDigits: 2,
                          ).format(_project.grandTotal),
                          style: const TextStyle(
                            fontSize: 24,
                            fontWeight: FontWeight.w900,
                            letterSpacing: -0.8,
                            color: AppTheme.amber,
                          ),
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(height: 16),

                  SizedBox(
                    width: double.infinity,
                    child: OutlinedButton.icon(
                      onPressed: _shareQuote,
                      icon: const Icon(Icons.share_outlined, size: 16),
                      label: const Text('Share Quote'),
                    ),
                  ),
                ]),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _ProjectHero extends StatelessWidget {
  final TileProject project;
  const _ProjectHero({required this.project});

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: const BoxDecoration(
        gradient: LinearGradient(
          colors: [AppTheme.bg, Color(0xFF1A1500)],
          begin: Alignment.topCenter,
          end: Alignment.bottomCenter,
        ),
      ),
      child: SafeArea(
        bottom: false,
        child: Padding(
          padding: const EdgeInsets.fromLTRB(20, 52, 20, 20),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              TmStatusBadge.fromStatus(project.status.name),
              const SizedBox(height: 6),
              Text(
                project.name,
                style: const TextStyle(
                  fontSize: 26,
                  fontWeight: FontWeight.w900,
                  letterSpacing: -0.8,
                  color: AppTheme.textHigh,
                ),
              ),
              if (project.clientName != null)
                Text(
                  project.clientName!,
                  style: const TextStyle(
                      fontSize: 13, color: AppTheme.textMid),
                ),
            ],
          ),
        ),
      ),
    );
  }
}

class _InfoRow extends StatelessWidget {
  final IconData icon;
  final String text;
  const _InfoRow(this.icon, this.text);

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4),
      child: Row(
        children: [
          Icon(icon, size: 14, color: AppTheme.textLow),
          const SizedBox(width: 8),
          Expanded(
            child: Text(text,
                style: const TextStyle(
                    fontSize: 13, color: AppTheme.textMid)),
          ),
        ],
      ),
    );
  }
}

class _RoomCard extends StatelessWidget {
  final TileCalculation room;
  final String currencySymbol;
  final VoidCallback onViewResult;
  final VoidCallback onDelete;

  const _RoomCard({
    required this.room,
    required this.currencySymbol,
    required this.onViewResult,
    required this.onDelete,
  });

  @override
  Widget build(BuildContext context) {
    final cost = NumberFormat.currency(
      symbol: currencySymbol,
      decimalDigits: 2,
    ).format(room.totalCost);

    return TmCard(
      onTap: onViewResult,
      child: Row(
        children: [
          Container(
            width: 40,
            height: 40,
            decoration: BoxDecoration(
              color: AppTheme.amberGlow,
              borderRadius: BorderRadius.circular(10),
            ),
            child: const Icon(Icons.grid_on, size: 18, color: AppTheme.amber),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  room.roomName,
                  style: const TextStyle(
                    fontSize: 14,
                    fontWeight: FontWeight.w700,
                    color: AppTheme.textHigh,
                  ),
                ),
                Text(
                  '${room.floorArea.toStringAsFixed(2)} m²  ·  '
                  '${room.tileLength.toStringAsFixed(0)}×${room.tileWidth.toStringAsFixed(0)}${room.tileUnit.label}  ·  '
                  '${room.boxesRequired} boxes',
                  style: const TextStyle(
                      fontSize: 11, color: AppTheme.textMid),
                ),
              ],
            ),
          ),
          Column(
            crossAxisAlignment: CrossAxisAlignment.end,
            children: [
              Text(
                cost,
                style: const TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.w800,
                  color: AppTheme.amber,
                ),
              ),
              const SizedBox(height: 2),
              GestureDetector(
                onTap: onDelete,
                child: const Icon(Icons.delete_outline,
                    size: 16, color: AppTheme.textLow),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

